import React from 'react';
import { Box, Drawer, Grid, Typography } from '@mui/material';
import { Controller, useForm } from 'react-hook-form';
import * as yup from 'yup';
import {
  formatISTtoTime,
  getTimeDifferenceInMinutes
} from '../../../../../utils/commonFunctions';
import { yupResolver } from '@hookform/resolvers/yup';
import { autoGenerateUpdateTripsAction } from '../../../redux/reducer/autoPlannerSlices/autoGenerateSlice';

import CustomButton from '../../../../../common/components/buttons/CustomButton';
import { useAppDispatch, useAppSelector } from '../../../../../app/redux/hooks';
import {
  useUpdateScheduledStates,
  useUpdateScheduleEffect,
  useUpdateScheduleOptions,
  useUpdateScheduleTripActions
} from './updateScheduleTripHook';
import UpdateScheduledTripFields from './updateScheduledTripFields';
import { clearDriverName } from '../../../redux/reducer/autoPlannerSlices/autoplanner';

interface Props {
  isUpdate: boolean;
  setIsUpdate: React.Dispatch<React.SetStateAction<boolean>>;
  selectedRow: any;
  autoplannerID: any;
  tripMode?: any;
  filterPayload?: any;
}

const UpdateScheduleTrip = ({
  isUpdate,
  setIsUpdate,
  selectedRow,
  filterPayload,
  autoplannerID,
  tripMode
}: Props) => {
  const dispatch = useAppDispatch();

  const {
    minPickTime,
    setMinPickTime,
    maxPickTime,
    setMaxPickTime,
    external,
    setExternal,
    timeDif,
    setTimeDif,
    validationErrors,
    setValidationErrorsMake
  } = useUpdateScheduledStates();

  const { isLoading } = useAppSelector(state => state.AutoGeneratedUpdateTrip);
  const { data, isLoading: dropdownLoading } = useAppSelector(
    state => state.getStandardVehicles
  );

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  const tripSchema = (isReturn: boolean) =>
    yup.object().shape({
      vehicle: yup
        .string()
        .oneOf(['internal', 'external'])
        .required('Select vehicle type'),
      vehicleNumber: yup.string().when('vehicle', {
        is: 'internal',
        then: () => yup.string().required('Select vehicle number'),
        otherwise: () =>
          yup
            .string()
            .required('Enter vehicle number')
            .matches(/^[A-Za-z0-9]*$/, 'Only letters and numbers allowed without spaces')
            .test(
              'valid-length',
              'Enter a valid vehicle number',
              value => (value?.length || 0) >= 4
            )
            .max(20, 'Maximum 20 characters')
            .test('has-letter', 'Must include at least one letter', value =>
              /[A-Za-z]/.test(value || '')
            )
            .test('has-number', 'Must include at least one number', value =>
              /[0-9]/.test(value || '')
            )
      }),
      driverName: yup.string().when('vehicle', {
        is: 'external',
        then: () => yup.string().required('Enter Driver Name'),
        otherwise: () => yup.string().notRequired()
      }),
      passengerCount: yup.string().when('vehicle', {
        is: 'external',
        then: () =>
          yup
            .number()
            .required('Enter Seat Capacity')
            .min(
              selectedRow?.netCount ? selectedRow?.netCount : 1,
              `Seat Capacity must be minimum ${selectedRow?.netCount}`
            )
            .max(250, 'Seat Capacity must be less than or equal to 250')
            .typeError(
              `Seat Capacity must be a number and minimum ${selectedRow?.netCount}`
            ),
        otherwise: () => yup.string().notRequired()
      }),

      driverNumber: yup.string().when('vehicle', {
        is: 'external',
        then: schema =>
          schema
            .required('Enter driver contact number')
            .test(
              'contactNumber-error',
              'Enter a valid contact number',
              function (value: any) {
                if (value && validationErrors.driverNumber !== 'no-error') {
                  return this.createError({ message: validationErrors.driverNumber });
                } else {
                  return true;
                }
              }
            ),
        otherwise: () => yup.string().notRequired()
      }),

      picktime1: isReturn
        ? yup.date().notRequired()
        : yup
            .date()
            .required('Choose from time')
            .test('is-valid-time', 'Invalid time format', value => {
              return true || null;
            }),
      picktime2: !selectedRow?.isReturnTrip
        ? yup
            .date()
            .required('Choose to time')
            .test(
              'is-after-picktime1',
              'Pickup time to must be 30 min',
              function (value) {
                const { picktime1 } = this.parent;
                if (!picktime1 || !value) {
                  return true || null;
                }
                const pickTime1Date = new Date(picktime1);
                const pickTime2Date = new Date(value);
                return pickTime2Date >= pickTime1Date;
              }
            )
        : yup.date().notRequired(),
      returnTime: !isReturn
        ? yup.object().required('Choose Return Time')
        : yup.object().notRequired()
    });

  const { standardVehicles } = useUpdateScheduleOptions(data);

  const {
    control,
    handleSubmit,
    setValue,
    clearErrors,
    getValues,
    reset,
    trigger,
    formState: { errors }
  } = useForm({
    defaultValues: {
      vehicle: 'internal'
    },
    resolver: yupResolver(tripSchema(selectedRow.isReturnTrip))
  });

  const { handleClose, handleMinTime, handleValidate } = useUpdateScheduleTripActions({
    setValidationErrorsMake,
    setIsUpdate,
    reset,
    setMinPickTime,
    setMaxPickTime,
    autoplannerID,
    setValue
  });

  const onSubmit = async (params: any) => {
    let payload: any = {
      id: selectedRow.id,
      tourName: selectedRow.tourName,
      pickupWindow: !selectedRow.returnTime
        ? `${formatISTtoTime(params?.picktime1)}-${formatISTtoTime(params?.picktime2)}`
        : null,
      returnTime: selectedRow.returnTime ? formatISTtoTime(params.returnTime) : null,
      totalAdultCount: selectedRow.totalAdultCount,
      totalChildCount: selectedRow.totalChildCount,
      netCount: selectedRow.netCount,
      isExternalVehicle: external ? 0 : 1,
      vehicleNumber: params?.vehicleNumber || selectedRow.vehicleNumber,
      isReturnTrip: selectedRow.isReturnTrip,
      driverName: selectedRow.driverName,
      driverID: selectedRow.driverID,
      driverContactNumber: selectedRow.driverContactNumber,
      modifyVehicleDriver: null,
      externalVehicleView: external
        ? null
        : {
            vehicleNumber: params?.vehicleNumber,
            driverName: params?.driverName,
            driverID: `${params?.driverName}${params?.driverNumber}`,
            mobileNumber: params?.driverNumber,
            seatingCapacity: params.passengerCount
          }
    };
    const pageDetails = {
      autoplannerID: autoplannerID,
      tripMode: tripMode,
      ...filterPayload
    };

    const data = { payload, pageDetails };
    const action = await dispatch(autoGenerateUpdateTripsAction(data as any));
    if (action.type === autoGenerateUpdateTripsAction.fulfilled.type) {
      handleClose();
      dispatch(clearDriverName());
    }
  };

  useUpdateScheduleEffect({
    validationErrors,
    trigger,
    autoplannerID,
    tripMode,
    selectedRow,
    dispatch,
    setTimeDif,
    getTimeDifferenceInMinutes,
    setValue,
    setExternal,
    getValues,
    handleMinTime
  });

  return (
    <>
      <Box className='add-trip-component'>
        <Box p={2}>
          <Drawer
            anchor='right'
            open={isUpdate}
            onClose={() => {
              reset();
              handleClose();
            }}
            sx={{ zIndex: 1 }}
          >
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
                gap: '15px !important'
              }}
              className='animate__animated animate__slideInUp'
            >
              <Box
                sx={{ display: 'flex', flexDirection: 'column', gap: 15 }}
                className='maintenance-container'
              ></Box>

              <Grid item xs={12} className='add-trip-grid-item'>
                <Box className='add-trip-header'>
                  <Typography
                    className='add-trip-title'
                    sx={{ fontSize: '24 px', fontWeight: 600 }}
                  >
                    Update Tour
                  </Typography>
                </Box>
                <Box component={'form'} onSubmit={handleSubmit(onSubmit)}>
                  <UpdateScheduledTripFields
                    control={control}
                    getValues={getValues}
                    setValue={setValue}
                    clearErrors={clearErrors}
                    setExternal={setExternal}
                    standardVehicles={standardVehicles}
                    dropdownLoading={dropdownLoading}
                    external={external}
                    errors={errors}
                    handleValidate={handleValidate}
                    trigger={trigger}
                    selectedRow={selectedRow}
                    handleMinTime={handleMinTime}
                    timeDif={timeDif}
                    minPickTime={minPickTime}
                    maxPickTime={maxPickTime}
                  />

                  <Box mt={3} mb={2} sx={{ textAlign: 'right' }}>
                    <CustomButton
                      category='Cancel'
                      className='cancel'
                      sx={{ marginRight: '10px' }}
                      onClick={() => handleClose()}
                    />
                    <CustomButton
                      category={'Save'}
                      className='saveChanges'
                      type='submit'
                      loading={isLoading}
                    />
                  </Box>
                </Box>
              </Grid>
            </Box>
          </Drawer>
        </Box>
      </Box>
    </>
  );
};

export default UpdateScheduleTrip;
