import {
  Box,
  Tooltip,
  Typography,
  Paper,
  Chip,
  useMediaQuery,
  Divider,
  Switch,
  DialogTitle,
  Grid,
  Dialog,
  DialogContent,
  DialogActions,
  Button,
  IconButton,
  Avatar,
  useTheme,
  Badge
} from '@mui/material';
import { useAppDispatch, useAppSelector } from '../../../../app/redux/hooks';
import CustomDataGrid from '../../../../common/components/customized/customdatagrid/CustomDataGrid';
import {
  getStandardDriverNames,
  getStandardVehicles,
  clearDriverNames
} from '../../redux/reducer/autoPlannerSlices/autoGenerateSlice';
import CustomTextField from '../../../../common/components/customized/customtextfield/CustomTextField';
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';
import { Controller, useForm } from 'react-hook-form';
import WhatsAppIcon from '@mui/icons-material/WhatsApp';
import nodata from '../../../../app/assets/images/nodata.png.png';

import * as yup from 'yup';
import { capitalizeFirstLetter, isValidField } from '../../../../utils/commonFunctions';
import { Icon } from '@iconify/react';

import CustomButton from '../../../../common/components/buttons/CustomButton';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import TourDashboard from '../trips/scheduled/TourDashboard';
import PhoneNoTextField from '../../../../common/components/customized/customtextfield/PhoneNoTextField';
import { yupResolver } from '@hookform/resolvers/yup';
import constant from '../../../../utils/constants';
import CustomSelect from '../../../../common/components/customized/customselect/CustomSelect';
import { Close, DirectionsCar } from '@mui/icons-material';
import CustomRadioButton from '../../../../common/components/customized/customradiobutton/CustomRadioButton';

import AddAdhocTrip from './components/AddAdhocTrip';
import PostAddIcon from '@mui/icons-material/PostAdd';
import AssignmentTurnedInOutlinedIcon from '@mui/icons-material/AssignmentTurnedInOutlined';
import ViewAdhocRequests from '../trips/scheduled/components/ViewAdhocRequests';
import {
  useCommonFunctions,
  useCommonStates
} from './hooks/todaytourshook/todayToursHooks';
import { useBookingsAction } from './hooks/todaytourshook/bookingsHook';
import { useJobActions } from './hooks/todaytourshook/jobsHook';
import { useWhatsappAction } from './hooks/todaytourshook/shareWhatsappHook';
import { useAdhocFunction } from './hooks/todaytourshook/adhocHook';

const TodayTours = () => {
  const { data, count, isLoading, statusCount } = useAppSelector(state => state.getExcel);
  const { data: ViewAdhocReqData } = useAppSelector(state => state.tripGRP);
  const { isLoading: updateGuestLoading } = useAppSelector(state => state.contactguest);
  const { isLoading: onsubmitIsLoading } = useAppSelector(
    state => state.AutoGeneratedUpdateTrip
  );
  const { data: vehicleDropdown, isLoading: dropdownLoading } = useAppSelector(
    state => state.getStandardVehicles
  );
  const { data: DriverNames, isLoading: DriverNameLoading } = useAppSelector(
    state => state.getStandardDriverNames
  );
  const { isLoading: updatePVTLoading } = useAppSelector(
    state => state.updatePvtGrpScheduled
  );
  const { isLoading: sicIsLoading } = useAppSelector(state => state.sicBookingsUpdate);
  const {
    data: groupData,
    count: groupCount,
    statusCount: groupStatusCount,
    isLoading: groupStatusLoading
  } = useAppSelector((state: any) => state.todayTours);
  const profileData = useAppSelector(
    state => state.myProfile.data || { timezone: '', userName: '' }
  );
  const sendwhatsapp = useAppSelector(state => state.sendwhatsapp);
  const { data: roles } = useAppSelector(state => state.auth);
  let roleType = roles?.role;
  const { category } = useAppSelector(state => state.RoleModuleAccess);
  const profileLoading = useAppSelector(state => state.myProfile.isLoading);
  const AutoPlannerDeleteTripLoading = useAppSelector(
    state => state.AutoPlannerDeleteTrip.isLoading
  );
  const PVTGRPUpdateLoading = useAppSelector(
    state => state.updatePvtGrpScheduled.isLoading
  );
  const Agents = useAppSelector(state => state.autoPlannerAgent.data || []);
  const driverName = useAppSelector(state => state.externalvalidation.data);

  const externalvehicleLoading = useAppSelector(
    state => state.externalvalidation.isLoading
  );

  const {
    invalidRows,
    setInvalidRows,
    PageSize,
    setPageSize,
    PageNo,
    setPageNo,
    selectedRow,
    setSelectedRow,
    searchEvent,
    setSearchEvent,
    scheduleDate,
    setScheduleDate,
    timeZone,
    setTimeZone,
    groupView,
    setGroupView,
    isDialog,
    setIsDialog,
    selectedTripRow,
    setSelectedTripRow,
    sendWhatsApp,
    setSendWhatsApp,
    validationErrors,
    setValidationErrorsMake,
    callApi,
    setCallApi,
    refreshLoader,
    setRefreshLoader,
    badgeCount,
    setBadgeCount
  } = useCommonStates();

  const autoplannerID = scheduleDate;

  const { control: phoneControl, setValue: settingValue, reset } = useForm({});

  const standardVehicles =
    vehicleDropdown?.length > 0
      ? vehicleDropdown?.map((value: string, index: number) => ({
          id: value,
          label: value?.toUpperCase()
        }))
      : [];

  const driverNameDropdown =
    DriverNames?.length > 0
      ? DriverNames?.map((value: any) => ({
          ...value,
          id: value?.driverID,
          label: value?.driverName?.toUpperCase()
        }))
      : [];
  const defaultVehilceNumber = [
    {
      id: selectedRow?.vehicleNumber,
      label: selectedRow?.vehicleNumber?.toUpperCase()
    }
  ];

  const vehicleSchema = yup.object().shape({
    vehicle: yup
      .string()
      .oneOf(['internal', 'external'])
      .required('Select vehicle type')
      .default('internal'),
    vehicleNumber: yup.string().when('vehicle', {
      is: 'internal',
      then: () => yup.string().required('Select vehicle number'),
      otherwise: () =>
        yup

          .string()
          .required('Enter vehicle number')
          .matches(/^[A-Za-z0-9]*$/, 'Only letters and numbers allowed without spaces')
          .test(
            'valid-length',
            'Enter a valid vehicle number',
            value => (value?.length || 0) >= 4
          )
          .max(20, 'Maximum 20 characters')
          .test('has-letter', 'Must include at least one letter', value =>
            /[A-Za-z]/.test(value || '')
          )
          .test('has-number', 'Must include at least one number', value =>
            /[0-9]/.test(value || '')
          )
    }),
    driverName: yup.string().when('vehicle', {
      is: 'external',
      then: () =>
        yup
          .string()
          .required('Enter driver name')
          .min(3, 'Driver name must be more than 2 characters')
          .matches(/^[a-zA-Z\s]+$/, 'Driver name must only contain characters'),
      otherwise: () => yup.string().required('Select driver name')
    }),
    passengerCount: yup.string().when('vehicle', {
      is: 'external',
      then: () =>
        yup
          .number()
          .required('Enter seating capacity')
          .min(
            selectedRow?.netCount ? selectedRow?.netCount : 1,
            `Seat Capacity Must be Minimum ${
              selectedRow?.netCount ? selectedRow?.netCount : 1
            }`
          )
          .max(249, 'Maximum absolute seating is 249')
          .transform((value, originalValue) => {
            return originalValue === '' ? undefined : value;
          })
          .typeError('Enter valid absolute seating'),

      otherwise: () => yup.string().notRequired()
    }),
    driverNumber: yup.string().when('vehicle', {
      is: 'external',
      then: () =>
        yup
          .string()
          .required('Enter contact number')
          // .trim()
          .test('basic-contact', 'Invalid contact number', value => {
            if (!value) return true;
            const phoneRegex = /^\+?[0-9]{1,4}[- ]?[0-9]{7,15}$/;
            return phoneRegex.test(value);
          })
          // .test('is-number', 'Enter contact number', function (value: any) {
          //   return value;
          // })
          .test('phone-errora', 'Invalid contact number', function (value: any) {
            if (value && validationErrors?.driverNumber !== 'no-error') {
              return this.createError({ message: validationErrors?.driverNumber });
            } else {
              return true;
            }
          }),
      otherwise: () => yup.string().notRequired()
    })
  });

  const APsuperAdmin = roleType === 'ROLE_AUTOPLANNER_ADMIN';
  const APoperator = roleType === 'ROLE_OPERATOR';
  const APagent = roleType === 'ROLE_AGENT';
  const APsubAgent = roleType === 'ROLE_SUB_AGENT';
  const APOperationUser = category === 'OPERATION_USER';

  const isAP = APsuperAdmin || APoperator || APagent || APsubAgent || APOperationUser;

  const theme = useTheme();
  const isMdUp = useMediaQuery(theme.breakpoints.up('md'));

  const {
    control,
    handleSubmit: vehicelsubmit,
    getValues,
    setValue: setVehicleValue,
    trigger,
    reset: externalReset,
    clearErrors: clearExternalVehicleErrors,
    formState: { errors: vehicleErrors }
  } = useForm({
    // defaultValues: {
    //   vehicle: 'internal'
    // },
    resolver: yupResolver(vehicleSchema)
  });
  const defaultDriverName = [
    {
      id:
        selectedRow?.standardTourOverview?.driverID ||
        selectedRow?.customTourOverview?.driverID ||
        '',

      label:
        selectedRow?.standardTourOverview?.driverName?.toUpperCase() ||
        selectedRow?.customTourOverview?.driverName?.toUpperCase() ||
        ''
    }
  ];

  const schema: any = () =>
    yup.object().shape({
      phone: yup
        .string()
        .trim()
        .required('Enter contact number')
        .test('basic-contact', 'Invalid contact number', value => {
          if (!value) return true;
          const phoneRegex = /^\+?[0-9]{1,4}[- ]?[0-9]{7,15}$/;
          return phoneRegex.test(value);
        })
        .test('is-number', 'Enter contact number', function (value: any) {
          return value;
        })
        .test('phone-error', 'Enter valid contact number', function (value: any) {
          if (validationErrors?.phone && value && validationErrors.phone !== 'no-error') {
            return this.createError({ message: validationErrors.phone });
          } else {
            return true;
          }
        })
    });

  const isSm = useMediaQuery('(max-width:700px)');
  const isXs = useMediaQuery('(max-width:575px');
  const isShare = useMediaQuery('(max-width:595px)');

  const dispatch = useAppDispatch();

  const status = [
    'Upcoming',
    'Completed',
    'In-transit',
    'Skipped',

    'Yet to onboard',
    'Onboarded',
    'No show',
    'Skipped'
  ];

  const agentNames =
    Agents?.map((value: string) => ({
      id: value,
      label: capitalizeFirstLetter(value)
    })) || [];

  const {
    control: formControl,
    setValue,
    reset: restToggle,
    trigger: phoneTrigger,
    formState: { errors },
    clearErrors,
    reset: internalReset,
    handleSubmit: onsubmit
  } = useForm({ resolver: yupResolver(schema()) });

  const isOverview = [
    groupView && (APoperator || APsuperAdmin || APOperationUser),
    !groupView && !(APoperator || APsuperAdmin || APOperationUser)
  ]?.some(item => item);

  //hooks
  const {
    handleHotelsandGuestsView,
    hotelGuestView,
    setHotelGuestView,
    handleOpenDialog,
    handleCancel,
    onvehicleSubmit,
    open,
    external,
    setExternal,
    groupColumns
  } = useJobActions({
    setCallApi,
    setSelectedRow,
    setVehicleValue,
    setValidationErrorsMake,
    clearExternalVehicleErrors,
    internalReset,
    externalReset,
    selectedRow,
    driverNameDropdown,
    scheduleDate,
    PageSize,
    isOverview,
    setPageNo
  });

  const { handleGuestContactChange, onChangeNumberSubmit, columns, handleClose } =
    useBookingsAction({
      setInvalidRows,
      autoplannerID,
      selectedTripRow,
      PageNo,
      PageSize,
      scheduleDate,
      searchEvent,
      restToggle,
      clearErrors,
      APsubAgent,
      APagent,
      setCallApi,
      setIsDialog,
      setSelectedTripRow,
      timeZone,
      setValue
    });

  const {
    handleSkip,
    handleSendWhatsapp,
    handleUpdateContact,
    handleInvalidClose,
    rows,
    invalidColumns
  } = useWhatsappAction({
    scheduleDate,
    setIsDialog,
    clearErrors,
    setCallApi,
    setValue,
    restToggle,
    setSendWhatsApp,
    invalidRows,
    autoplannerID,
    setInvalidRows,
    validationErrors,
    phoneTrigger,
    sendwhatsapp,
    data,
    isLoading,
    handleGuestContactChange,
    count
  });

  const currentDatas = {
    data: isOverview ? groupData : rows,
    isLoading: isOverview ? groupStatusLoading : isLoading,
    count: isOverview ? groupCount : count,
    statusCount: isOverview ? groupStatusCount : statusCount,
    columns: isOverview ? groupColumns : columns
  };

  const {
    AntSwitch,
    handlePaginationModelChange,
    handleFilterChange,
    getCurrentDate,
    getStatusColor,
    handleGroupView,
    handleDeleteDriver,
    handleValidate,
    filter,
    isViewAdhoc,
    setIsViewAdhoc
  } = useCommonFunctions({
    setRefreshLoader,
    setPageSize,
    setPageNo,
    scheduleDate,
    searchEvent,
    isOverview,
    PageSize,
    setSearchEvent,
    PageNo,
    timeZone,
    setGroupView,
    setValue,
    selectedTripRow,
    APagent,
    APsubAgent,
    setIsDialog,
    autoplannerID,
    setBadgeCount,
    setValidationErrorsMake,
    currentDatas,
    callApi,
    setScheduleDate,
    APoperator,
    APsuperAdmin,
    APOperationUser,
    groupView,
    profileData,
    setTimeZone,
    setSendWhatsApp,
    restToggle,
    setCallApi,
    clearErrors,
    setVehicleValue,
    validationErrors,
    trigger
  });

  const { handlePaginationAdhocReq, adhocReqColumns } = useAdhocFunction({
    setRefreshLoader,
    setPageSize,
    setPageNo,
    autoplannerID,
    setBadgeCount,
    ViewAdhocReqData,
    APsubAgent,
    APagent,
    setCallApi,
    setIsDialog,
    setSelectedTripRow,
    isAP
  });

  return (
    <>
      {!isViewAdhoc ? (
        <Box
          sx={{
            padding: 3
          }}
        >
          {!hotelGuestView && (
            <Paper
              elevation={0}
              sx={{
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                borderRadius: 2,
                p: { xs: 1.5, sm: 1.5 },
                mb: 1,
                color: 'white',
                position: 'relative',
                overflow: 'hidden'
              }}
            >
              <Box
              // sx={{
              //   position: 'absolute',
              //   top: -10,
              //   right: -10,
              //   width: 60,
              //   height: 60,
              //   background: 'rgba(255, 255, 255, 0.15)',
              //   borderRadius: '50%'
              // }}
              />
              <Box sx={{ position: 'relative', zIndex: 1 }}>
                <Grid container spacing={0.5}>
                  {/* Left Section */}
                  <Grid item xs={12} sm={12} md={4}>
                    <Box
                      sx={{
                        height: '100%',
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'center',
                        gap: 1
                      }}
                    >
                      <Typography
                        variant='h4'
                        sx={{
                          fontWeight: 'bold',
                          marginBottom: 0.5,
                          background: 'linear-gradient(45deg, #ffffff, #f0f8ff)',
                          backgroundClip: 'text',
                          WebkitBackgroundClip: 'text',
                          WebkitTextFillColor: 'transparent',
                          display: 'flex',
                          alignItems: 'center',
                          fontSize: { xs: '1.0rem', md: '1.5rem' }
                        }}
                      >
                        <Icon
                          icon='tdesign:vehicle-filled'
                          width='24'
                          height='24'
                          style={{ marginRight: '10px' }}
                        />
                        {/* Today's Jobs */}
                        Live Dashboard{' '}
                      </Typography>
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                        <Icon
                          icon='lets-icons:date-fill'
                          width='20'
                          height='20'
                          style={{ color: '#dce5ff' }}
                        />
                        <Typography
                          variant='body2'
                          sx={{
                            opacity: 0.9,
                            fontWeight: 300,
                            fontSize: '0.9rem'
                          }}
                        >
                          {getCurrentDate()}
                        </Typography>
                      </Box>
                    </Box>
                  </Grid>

                  {isOverview && (
                    <>
                      <Grid item xs={12} sm={12} md={3.8} lg={3.9}>
                        <Box>
                          <Typography
                            sx={{
                              fontSize: '12px',
                              fontWeight: 'bold',
                              display: 'flex',
                              justifyContent: 'center',
                              marginBottom: '6px'
                            }}
                          >
                            Jobs -{' '}
                            {(currentDatas.statusCount['Upcoming'] ?? 0) +
                              (currentDatas.statusCount['In-transit'] ?? 0) +
                              (currentDatas.statusCount['Completed'] ?? 0) +
                              (currentDatas.statusCount['Trip Skipped'] ?? 0)}
                          </Typography>
                          <Grid
                            container
                            spacing={0.1}
                            sx={{
                              flexDirection: { xs: 'row', lg: 'row' },
                              flexWrap: { xs: 'wrap', lg: 'nowrap' },
                              gap: { lg: 1, xs: 0 }
                            }}
                          >
                            {status
                              ?.filter((_, index) => index < 4)
                              ?.map((item: any) => {
                                const count =
                                  item === 'Total'
                                    ? (currentDatas.statusCount['Upcoming'] ?? 0) +
                                      (currentDatas.statusCount['In-transit'] ?? 0) +
                                      (currentDatas.statusCount['Completed'] ?? 0) +
                                      (currentDatas.statusCount['Trip Skipped'] ?? 0)
                                    : currentDatas.statusCount[
                                        item === 'Skipped' ? 'Trip Skipped' : item
                                      ] ?? 0;

                                return (
                                  <Grid item xs={6} sm={3} md={6} key={item}>
                                    <Chip
                                      size='small'
                                      label={`${item} - ${count}`}
                                      sx={{
                                        width: '100%',
                                        justifyContent: 'center',
                                        border: `1px solid ${getStatusColor(item)}`,
                                        backgroundColor: '#fff',
                                        color: getStatusColor(item),
                                        fontWeight: 600,
                                        fontSize: '0.7rem',
                                        borderRadius: '8px',
                                        boxShadow: '0 1px 2px rgba(0,0,0,0.06)',
                                        transition: 'all 0.2s ease'
                                      }}
                                    />
                                  </Grid>
                                );
                              })}
                          </Grid>
                        </Box>
                      </Grid>

                      <Grid
                        item
                        xs={12}
                        lg={0.15}
                        md={0.1}
                        sx={{
                          display: 'flex',
                          justifyContent: 'center',
                          alignItems: 'center'
                        }}
                      >
                        <Divider
                          flexItem
                          orientation={isMdUp ? 'vertical' : 'horizontal'}
                          sx={{
                            backgroundColor: 'rgba(255, 255, 255, 0.5)',
                            borderRadius: 1,
                            // height: isMdUp ? '60% !important' : '1px !important',
                            // width: isMdUp ? '1px !important' : '60% !important'
                            height: isMdUp ? '100%' : '1px',
                            width: isMdUp ? '1px' : '100%'
                          }}
                        />
                      </Grid>
                    </>
                  )}

                  <Grid
                    item
                    xs={12}
                    sm={12}
                    md={!isOverview ? 8 : 3.9}
                    lg={3.9}
                    sx={{
                      ml: !isOverview ? 'auto' : 0
                      // display: 'flex'
                    }}
                  >
                    <Box>
                      <Typography
                        sx={{
                          fontSize: '12px',
                          fontWeight: 'bold',
                          display: 'flex',
                          justifyContent: 'center',
                          marginBottom: '6px'
                        }}
                      >
                        Bookings - {currentDatas.statusCount['Total'] ?? 0}
                      </Typography>
                      <Grid
                        container
                        spacing={0.1}
                        sx={{
                          flexDirection: { xs: 'row', lg: 'row' },
                          flexWrap: { xs: 'wrap', lg: 'nowrap' },
                          gap: { lg: 0.5, xs: 0 }
                        }}
                      >
                        {status
                          ?.filter((_, index) => index > 3)
                          ?.map((item: any) => (
                            <Grid
                              item
                              xs={6}
                              sm={3}
                              md={!isOverview ? 3 : 6}
                              lg={6}
                              key={item}
                            >
                              <Chip
                                size='small'
                                label={`${
                                  item === 'Yet to onboard' ? 'Yet to board' : item
                                } - ${currentDatas.statusCount[item] ?? 0}`}
                                sx={{
                                  width: '100%',
                                  justifyContent: 'center',
                                  border: `1px solid ${getStatusColor(item)}`,
                                  backgroundColor: '#fff',
                                  color: getStatusColor(item),
                                  fontWeight: 600,
                                  fontSize: '0.7rem',
                                  borderRadius: '8px',
                                  boxShadow: '0 1px 2px rgba(0,0,0,0.06)',
                                  transition: 'all 0.2s ease'
                                }}
                              />
                            </Grid>
                          ))}
                      </Grid>
                    </Box>
                  </Grid>
                </Grid>
              </Box>
            </Paper>
          )}
          {!hotelGuestView && (
            <>
              {(APoperator || APsuperAdmin || APOperationUser) && (
                <Box
                  sx={{
                    float: { lg: 'right', xs: 'left', sm: 'right', md: 'right' },
                    display: 'flex',
                    alignItems: 'center',
                    gap: 2
                  }}
                >
                  <Typography>Bookings</Typography>
                  <AntSwitch
                    tabIndex={0}
                    inputProps={{ 'aria-label': 'ant design' }}
                    className='ant-switch'
                    checked={groupView}
                    onChange={(e: any) => {
                      handleGroupView(e.target.checked);
                    }}
                    onKeyDown={event => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault();
                        handleGroupView(!groupView);
                      }
                    }}
                    onFocus={(e: any) => {
                      e.currentTarget.style.outline = '2px solid grey';
                      e.currentTarget.style.outlineOffset = '5px';
                    }}
                    onBlur={(e: any) => {
                      e.currentTarget.style.outline = 'none';
                    }}
                  />
                  <Typography>Jobs</Typography>
                </Box>
              )}
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: {
                    lg: 'flex-end',
                    sm: 'flex-end',
                    md: 'flex-end'
                  },
                  flexDirection: { xs: 'column', lg: 'row', sm: 'row', md: 'row' },
                  alignItems: 'center',
                  width: '100%'
                }}
              >
                <Box
                  sx={{
                    display: 'flex',
                    // justifyContent: {
                    //   lg: 'flex-end',
                    //   sm: 'flex-end',
                    //   md: 'flex-end'
                    // },
                    flexDirection: { xs: 'column', lg: 'row', sm: 'row', md: 'row' },
                    alignItems: 'center',
                    width: '100%',
                    gap: '20px'
                  }}
                >
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    {/* <Box
                  sx={{
                    background: 'linear-gradient(135deg, #648DB3  0%, #5459AC 100%)',
                    padding: '10px',
                    display: 'flex',
                    gap: '1rem',
                    borderRadius: '10px',
                    alignItems: 'center',
                    position: 'relative'
                  }}
                  onClick={handleTodayTrips}
                >
                  <Box>
                    <Typography color={'#fff'} fontSize={'1rem'} fontWeight={600}>
                      Refresh
                    </Typography>
                  </Box>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Icon
                      icon={'ph:arrows-clockwise'}
                      style={{
                        color: '#ffffff',
                        cursor: 'pointer',
                        fontSize: '20px',
                        userSelect: 'none'
                      }}
                      className={`activerIcon ${refresh ? 'refresh' : ''}`}
                    />
                  </Box>
                </Box> */}

                    <>
                      {isShare && currentDatas?.data?.length > 0 ? (
                        <Box
                          sx={{
                            display: 'flex',
                            alignItems: 'center',
                            gap: 1,
                            marginTop: 1,
                            position: { xs: 'relative' }
                          }}
                        >
                          <Tooltip enterDelay={200} leaveDelay={200} title={'Share Trip'}>
                            <Icon
                              icon='ic:sharp-whatsapp'
                              width='35'
                              height='35'
                              onClick={() => {
                                setIsDialog('whatsapp');
                                setCallApi(true);
                              }}
                              style={{
                                backgroundColor: '#25D366',
                                color: 'white',
                                borderRadius: '6px',
                                cursor: 'pointer',
                                padding: '6px',
                                display: 'flex',
                                alignItems: 'center',
                                justifyContent: 'center'
                              }}
                            />
                          </Tooltip>

                          {isAP && (
                            <Tooltip enterDelay={200} leaveDelay={200} title='Add Ad-hoc'>
                              <Icon
                                icon='material-symbols:post-add-rounded'
                                width='35'
                                height='35'
                                onClick={() => {
                                  setIsDialog('adhoc');
                                  setCallApi(true);
                                }}
                                style={{
                                  backgroundColor: '#0d9488',
                                  color: '#fff',
                                  borderRadius: '6px',
                                  cursor: 'pointer',
                                  padding: '6px',
                                  display: 'flex',
                                  alignItems: 'center',
                                  justifyContent: 'center'
                                }}
                              />
                            </Tooltip>
                          )}

                          {isAP && badgeCount > 0 && (
                            <Tooltip
                              title='View Ad-hoc Requests'
                              enterDelay={200}
                              leaveDelay={200}
                            >
                              <Badge
                                badgeContent={badgeCount}
                                color='primary'
                                anchorOrigin={{
                                  vertical: 'top',
                                  horizontal: 'right'
                                }}
                              >
                                <Box
                                  onClick={() => {
                                    setIsViewAdhoc(true);
                                    setCallApi(true);
                                  }}
                                  sx={{
                                    width: 35,
                                    height: 35,
                                    borderRadius: '6px',
                                    cursor: 'pointer',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    color: '#fff',
                                    background:
                                      'linear-gradient(135deg, #0d9488, #14b8a6)',
                                    boxShadow: '0 3px 8px rgba(0,0,0,0.2)',
                                    '&:active': { transform: 'scale(0.95)' }
                                  }}
                                >
                                  <AssignmentTurnedInOutlinedIcon sx={{ fontSize: 22 }} />
                                </Box>
                              </Badge>
                            </Tooltip>
                          )}
                        </Box>
                      ) : (
                        <>
                          {currentDatas?.data?.length > 0 && (
                            <Button
                              variant='contained'
                              className='whatsapp'
                              startIcon={<WhatsAppIcon />}
                              sx={{
                                backgroundColor: '#25D366',
                                color: 'white',
                                textTransform: 'none',
                                padding: '8px 20px',
                                borderRadius: '8px',
                                boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
                                '&:hover': { backgroundColor: '#1EBE57' }
                              }}
                              onClick={() => {
                                setIsDialog('whatsapp');
                                setCallApi(true);
                              }}
                            >
                              Share Trip
                            </Button>
                          )}

                          {(isAP || APsubAgent) && (
                            <Button
                              variant='contained'
                              startIcon={<PostAddIcon />}
                              sx={{
                                backgroundColor: '#0d9488',
                                color: 'white',
                                textTransform: 'none',
                                padding: '8px 20px',
                                borderRadius: '8px',
                                boxShadow: '0 1px 3px rgba(0,0,0,0.2)',
                                '&:hover': { backgroundColor: '#0b7c73' }
                              }}
                              onClick={() => {
                                setIsDialog('adhoc');
                                setCallApi(true);
                                setSelectedTripRow(null);
                              }}
                            >
                              Add Ad-hoc
                            </Button>
                          )}
                          {isAP && badgeCount > 0 && (
                            <Tooltip
                              title='View Ad-hoc Requests'
                              enterDelay={200}
                              leaveDelay={200}
                            >
                              <Badge
                                badgeContent={badgeCount}
                                color='primary'
                                anchorOrigin={{ vertical: 'top', horizontal: 'right' }}
                              >
                                <Box
                                  onClick={() => {
                                    setIsViewAdhoc(true);
                                    setCallApi(true);
                                  }}
                                  tabIndex={0}
                                  onKeyDown={(event: any) => {
                                    if (event.key === 'Enter' || event.key === ' ') {
                                      event.preventDefault();
                                      setIsViewAdhoc(true);
                                      setCallApi(true);
                                    }
                                  }}
                                  sx={{
                                    width: 38,
                                    height: 38,
                                    borderRadius: 2,
                                    cursor: 'pointer',
                                    display: 'flex',
                                    alignItems: 'center',
                                    justifyContent: 'center',
                                    color: '#fff',
                                    background:
                                      'linear-gradient(135deg, #0d9488, #14b8a6)',
                                    boxShadow: '0 3px 8px rgba(0,0,0,0.2)',
                                    // transition: 'transform 0.25s, box-shadow 0.25s',
                                    '&:hover': {
                                      // transform: 'scale(1.1)',
                                      boxShadow: '0 5px 12px rgba(0,0,0,0.25)'
                                    },
                                    '&:active': { transform: 'scale(0.95)' }
                                  }}
                                >
                                  <AssignmentTurnedInOutlinedIcon sx={{ fontSize: 22 }} />
                                </Box>
                              </Badge>
                            </Tooltip>
                          )}
                        </>
                      )}
                    </>
                  </Box>
                  {/* <Box
              sx={{
                background: 'linear-gradient(135deg, #648DB3  0%, #5459AC 100%)',
                padding: '10px',
                display: 'flex',
                gap: '1rem',
                borderRadius: '10px',
                alignItems: 'center',
                position: 'relative',
                cursor: 'pointer'
              }}
              onClick={handleTodayTrips}
            >
              <Box>
                <Typography color={'#fff'} fontSize={'1rem'} fontWeight={600}>
                  Refresh
                </Typography>
              </Box>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                <Icon
                  icon={'ph:arrows-clockwise'}
                  style={{
                    color: '#ffffff',
                    cursor: 'pointer',
                    fontSize: '20px',
                    userSelect: 'none'
                  }}
                  className={`activerIcon ${refresh ? 'refresh' : ''}`}
                />
              </Box>
            </Box> */}
                </Box>

                {(groupData?.length > 0 ||
                  (filter && groupData?.length === 0) ||
                  rows?.length > 0 ||
                  (filter && rows?.length === 0)) && (
                  <Box>
                    <CustomTextField
                      name='search'
                      control={formControl}
                      id='filter-input'
                      placeholder='Search...'
                      value={filter}
                      variant='standard'
                      icon={<SearchOutlinedIcon color='primary' />}
                      onChangeCallback={(e: any) => handleFilterChange(e)}
                    />
                  </Box>
                )}
              </Box>
            </>
          )}

          {isDialog === 'AddContact' && (
            <Dialog
              open={isDialog === 'AddContact'}
              onClose={handleClose}
              fullWidth
              maxWidth='md'
              PaperProps={{
                sx: {
                  borderRadius: { xs: 2, sm: 3, md: 4 },
                  background: 'linear-gradient(145deg, #ffffff, #f0f8ff)',
                  boxShadow: '0px 16px 40px rgba(0, 0, 0, 0.2)',
                  overflow: 'auto',
                  backdropFilter: 'blur(10px)',
                  mx: { xs: 2, sm: 3, md: 6, lg: 'auto' },
                  maxWidth: { xs: '100%', sm: 500, md: 500, lg: 500 }
                }
              }}
              BackdropProps={{
                sx: {
                  backgroundColor: 'rgba(0, 0, 0, 0.5)',
                  backdropFilter: 'blur(4px)'
                }
              }}
            >
              <Box
                padding={{ xs: 2, sm: 3, md: 4, lg: 5 }}
                width='100%'
                maxWidth={{ xs: '100%', sm: 500, md: 650, lg: 800 }}
                component='form'
                onSubmit={onsubmit(onChangeNumberSubmit)}
              >
                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: { xs: 'column-reverse', sm: 'row' },
                    justifyContent: 'space-between',
                    alignItems: { xs: 'stretch', sm: 'center' },
                    gap: 2,
                    mb: 3,
                    pb: 2,
                    borderBottom: '2px solid #e3f2fd'
                  }}
                >
                  <Box
                    sx={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: { xs: 'center', sm: 'flex-start' }
                    }}
                  >
                    <Icon
                      icon='ph:phone-plus'
                      style={{
                        fontSize: '26px',
                        color: '#1976d2',
                        marginRight: '12px'
                      }}
                    />
                    <Typography
                      sx={{
                        fontWeight: 700,
                        fontSize: { xs: '18px', sm: '20px', md: '22px', lg: '24px' },
                        color: '#1976d2'
                      }}
                    >
                      Guest Contact Information
                    </Typography>
                  </Box>
                </Box>

                <CustomTextField
                  id='guestName'
                  name='guestName'
                  placeholder='Guest Name'
                  control={formControl}
                  disabled
                  label='Guest Name'
                  defaultValue={selectedTripRow?.guestName || ''}
                  variant='outlined'
                />

                <Controller
                  name='phone'
                  control={formControl}
                  defaultValue=''
                  rules={{ required: true }}
                  render={({ field }: any) => (
                    <PhoneNoTextField
                      {...field}
                      setValue={setValue}
                      style='share'
                      label='Contact Number'
                      helperText={errors?.phone?.message}
                      error={!!errors?.phone?.message}
                      onChange={(e: any) => {
                        if (e) {
                          const emptySpace = /^.+\s.+$/g;
                          if (e && !emptySpace.test(e)) {
                            handleValidate(e, 'phone');
                          }
                        }
                        phoneTrigger('phone');
                      }}
                    />
                  )}
                />

                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: { xs: 'row', sm: 'row' },
                    alignItems: { xs: 'flex-start', sm: 'center' },
                    justifyContent: 'space-between',
                    mt: 3,
                    p: 2,
                    backgroundColor: '#f8fffe',
                    borderRadius: 2,
                    border: '1px solid #e8f5e8',
                    gap: { xs: 2, sm: 0 }
                  }}
                >
                  <Tooltip
                    title={
                      selectedTripRow?.vehicleNumber === 'Unassigned'
                        ? "Can't send WhatsApp for tours without vehicles"
                        : ''
                    }
                  >
                    <Box sx={{ display: 'flex', alignItems: 'center', flexGrow: '5' }}>
                      <Icon
                        icon='ic:baseline-whatsapp'
                        style={{
                          fontSize: '24px',
                          color: '#25d366',
                          marginRight: '12px'
                        }}
                      />
                      <Box>
                        <Typography
                          sx={{
                            fontWeight: 600,
                            fontSize: { xs: '13px', sm: '14px', md: '15px' },
                            color: '#333',
                            mb: '2px'
                          }}
                        >
                          Send WhatsApp Message
                        </Typography>
                        <Typography
                          sx={{
                            fontSize: { xs: '12px', sm: '13px' },
                            color: '#666'
                          }}
                        >
                          Enable to send notifications via WhatsApp
                        </Typography>
                      </Box>
                    </Box>
                  </Tooltip>
                  <Box>
                    <Controller
                      name='sendWhatsApp'
                      control={formControl}
                      defaultValue={false}
                      render={({ field }) => (
                        <Switch
                          checked={sendWhatsApp}
                          onChange={e => {
                            field.onChange(e.target.checked);
                            setSendWhatsApp(e.target.checked);
                          }}
                          disabled={selectedTripRow?.vehicleNumber === 'Unassigned'}
                        />
                      )}
                    />
                  </Box>
                </Box>

                <Box
                  sx={{
                    display: 'flex',
                    flexDirection: { xs: 'column-reverse', sm: 'row' },
                    justifyContent: 'flex-end',
                    gap: 2,
                    mt: 3,
                    pt: 2,
                    borderTop: '1px solid #e0e0e0'
                  }}
                >
                  <CustomButton
                    category='Cancel'
                    className='cancel'
                    sx={{
                      // borderRadius: 3,
                      // textTransform: 'none',
                      // fontWeight: 600,
                      px: { xs: 2.5, sm: 3 },
                      // py: 1.2,
                      width: { xs: '100%', sm: 'auto' },
                      fontSize: { xs: '0.9rem', sm: '1rem' }
                    }}
                    onClick={() => handleClose()}
                  />
                  <CustomButton
                    category={sendWhatsApp ? 'Save & Send' : 'Save'}
                    className='saveChanges'
                    loading={
                      selectedTripRow?.mode === 'PVT' || selectedTripRow?.mode === 'GRP'
                        ? updatePVTLoading || updateGuestLoading
                        : sicIsLoading || updateGuestLoading
                    }
                    type='submit'
                    sx={{
                      // borderRadius: 3,
                      // textTransform: 'none',
                      // fontWeight: 600,
                      px: { xs: 2.5, sm: 3 },
                      // py: 1.2,
                      width: { xs: '100%', sm: 'auto' },
                      fontSize: { xs: '0.9rem', sm: '1rem' }
                      // background: 'linear-gradient(45deg, #1976d2, #42a5f5)',
                      // '&:hover': {
                      //   background: 'linear-gradient(45deg, #1565c0, #1e88e5)'
                      // }
                    }}
                  />
                </Box>
              </Box>
            </Dialog>
          )}

          {!hotelGuestView &&
            ((currentDatas['isLoading'] || profileLoading) &&
            (currentDatas['data']?.length === 0 || currentDatas['data'] === null) ? (
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center'
                }}
              >
                <Box className='blue-circle-loader big-screen'>
                  <Box className='blue-circle-spinner'></Box>
                </Box>
              </Box>
            ) : currentDatas['data']?.length > 0 && currentDatas['data'] ? (
              <Box
                sx={{
                  borderRadius: 3,
                  overflow: 'auto',
                  background: 'white',
                  boxShadow: 'none',
                  height: { lg: '60vh', md: '60vh', sm: '45vh', xs: '34vh' },
                  scrollbarWidth: 'none',
                  marginTop: { lg: '12px', md: '12px', sm: '12px', xs: '12px' }
                }}
              >
                <CustomDataGrid
                  rows={currentDatas['data']}
                  columns={currentDatas['columns']}
                  type='logistics'
                  onPaginationModelChange={handlePaginationModelChange}
                  pageNo={PageNo}
                  rowCount={currentDatas['count']}
                  loading={currentDatas['isLoading'] && refreshLoader}
                  rowHeight={35}
                  pageSize={PageSize}
                  paginationModel={{
                    page: PageNo && currentDatas['count'] ? PageNo - 1 : 0,
                    pageSize: PageSize ? PageSize : 20
                  }}
                  onRowClick={(id: number, row: any) => {
                    if (isOverview) {
                      handleHotelsandGuestsView(row);
                    }
                  }}
                />
              </Box>
            ) : (
              <Box
                sx={{
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'center',
                  alignItems: 'center',
                  height: 400,
                  background: 'linear-gradient(145deg, #f8f9fa, #ffffff)',
                  textAlign: 'center',
                  padding: 4
                }}
              >
                <Box
                  component='img'
                  src={nodata}
                  alt='No Report Found'
                  sx={{
                    maxWidth: 200,
                    opacity: 0.7,
                    marginBottom: 2
                  }}
                />
                <Typography
                  variant='h6'
                  sx={{
                    color: '#666',
                    fontWeight: '500',
                    marginBottom: 1
                  }}
                >
                  No Trips Scheduled
                </Typography>
                <Typography
                  variant='body2'
                  sx={{
                    color: '#999',
                    maxWidth: 300
                  }}
                >
                  There are no scheduled trips for today.
                </Typography>
              </Box>
            ))}
          {open && (
            <Dialog
              open={open}
              maxWidth='xs'
              fullWidth
              PaperProps={{
                sx: {
                  borderRadius: 3,
                  boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
                }
              }}
            >
              <Box component={'form'} onSubmit={vehicelsubmit(onvehicleSubmit)}>
                <DialogTitle sx={{ p: 0 }}>
                  <Box
                    sx={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      p: 3,
                      borderBottom: '1px solid',
                      borderColor: 'divider'
                    }}
                  >
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                      <Avatar
                        sx={{
                          bgcolor: 'primary.light',
                          color: 'whites',
                          width: 40,
                          height: 40
                        }}
                      >
                        <DirectionsCar />
                      </Avatar>
                      <Box>
                        <Typography variant='h6' component='h2' sx={{ fontWeight: 600 }}>
                          Select Vehicle
                        </Typography>
                        <CustomRadioButton
                          name='vehicle'
                          control={control}
                          radiobutton1='Internal Vehicle'
                          radiobutton2='External Vehicle'
                          value={getValues('vehicle')}
                          value1='internal'
                          value2='external'
                          onChangeCallback={(e: any) => {
                            internalReset();
                            externalReset();
                            clearExternalVehicleErrors();
                            clearErrors();

                            setVehicleValue('vehicle', e.target.value);

                            clearErrors();

                            if (e.target.value === 'internal') {
                              setExternal(false);
                            } else {
                              setExternal(true);
                            }
                            let overview = null;
                            if (['SIC', 'TSIC'].includes(selectedRow?.mode)) {
                              overview = selectedRow?.standardTourOverview;
                            } else if (['PVT', 'GRP'].includes(selectedRow?.mode)) {
                              overview = selectedRow?.customTourOverview;
                            }
                            const payload = {
                              autoplannerID: selectedRow.date,
                              tripMode: selectedRow?.mode,
                              tourName: selectedRow?.tourName,
                              totalPassengers: selectedRow?.totalGuests,
                              vehicleNumber: selectedRow?.vehicleNumber,
                              isCurrentSchedule: true,
                              journeyId: overview?.journeyId || overview?.journeyId || ''
                            };
                            if (e.target.value !== 'external') {
                              dispatch(getStandardVehicles(payload));
                            }
                          }}
                        />
                      </Box>
                    </Box>
                    <IconButton
                      onClick={handleCancel}
                      sx={{
                        color: 'text.secondary',
                        '&:hover': {
                          color: 'text.primary'
                        }
                      }}
                    >
                      <Close />
                    </IconButton>
                  </Box>
                </DialogTitle>

                <DialogContent sx={{ p: 3, pt: 4 }}>
                  {!external ? (
                    <Box sx={{ mb: 2 }}>
                      <CustomSelect
                        isDisabled={dropdownLoading}
                        id='vehicleNumber'
                        control={control}
                        label='Vehicle Number'
                        name='vehicleNumber'
                        placeholder='Vehicle number'
                        options={
                          dropdownLoading ? defaultVehilceNumber : standardVehicles
                        }
                        loading={dropdownLoading}
                        onChanges={(id: any, value: any) => {
                          setVehicleValue('driverName', '');
                          dispatch(clearDriverNames());
                          const payload = {
                            autoplannerID: selectedRow.date,
                            tripMode: selectedRow?.mode,
                            tourName: selectedRow?.tourName,
                            totalPassengers: selectedRow?.totalGuests,
                            vehicleNumber: value?.id,
                            assignedVehicle: selectedRow?.vehicleNumber,
                            isCurrentSchedule: true,
                            journeyId:
                              selectedRow?.customTourOverview?.journeyId ||
                              selectedRow?.standardTourOverview?.journeyId ||
                              ''
                          };
                          if (value) {
                            dispatch(getStandardDriverNames(payload));
                          }
                        }}
                      />
                      <CustomSelect
                        isDisabled={DriverNameLoading || !getValues('vehicleNumber')}
                        id='drivername'
                        control={control}
                        label='Driver Name'
                        name='driverName'
                        placeholder='Driver name'
                        options={
                          DriverNameLoading ? defaultDriverName : driverNameDropdown
                        }
                        loading={DriverNameLoading}
                        onChanges={(_: any, value: any) => {
                          setVehicleValue('driverName', value?.id);
                        }}
                      />
                    </Box>
                  ) : (
                    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                      <Box>
                        <CustomTextField
                          id='vehicleNumber'
                          control={control}
                          name='vehicleNumber'
                          label='Vehicle Number'
                          maxlength={20}
                          placeholder='Vehicle number'
                          onChangeCallback={e => {
                            setVehicleValue('vehicleNumber', e);
                          }}
                        />
                      </Box>

                      <Controller
                        name='driverNumber'
                        control={control}
                        // rules={{ required: true }}
                        render={({ field }) => (
                          <PhoneNoTextField
                            {...field}
                            setValue={setVehicleValue}
                            country='sg'
                            disableCountry={true}
                            loading={externalvehicleLoading}
                            style='share'
                            label='Contact Number'
                            error={Boolean(vehicleErrors?.driverNumber?.message)}
                            helperText={vehicleErrors?.driverNumber?.message}
                            onChange={(e: any) => {
                              if (e) {
                                const emptySpace = /^.+\s.+$/g;
                                const isValid = isValidField('contactnumber', e);
                                if (e && !emptySpace.test(e) && isValid) {
                                  handleValidate(e, 'driverNumber');
                                } else if (e) {
                                  setVehicleValue('driverNumber', e);
                                } else {
                                  setVehicleValue('driverNumber', '');
                                }
                              }
                              trigger('driverNumber');
                            }}
                          />
                        )}
                      />

                      <Box>
                        <CustomTextField
                          id='driverName'
                          control={control}
                          name='driverName'
                          label='Driver Name'
                          disabled={driverName ? true : false}
                          placeholder='Driver name'
                          maxlength={60}
                          onChangeCallback={e => {
                            setVehicleValue('driverName', e);
                          }}
                        />
                      </Box>
                      <Box>
                        <CustomTextField
                          id='count'
                          control={control}
                          type='number'
                          name='passengerCount'
                          isDecimal
                          label='Seating Capacity'
                          placeholder='Seating capacity'
                          onChangeCallback={e => {
                            setVehicleValue('passengerCount', e);
                            clearErrors('passengerCount');
                          }}
                        />
                      </Box>

                      <Box>
                        {/* {errors?.phone?.message && (
                  <Box>
                    <CustomTextField
                      id='count'
                      control={control}
                      type='number'
                      name='passengerCount'
                      label='Seat Capacity'
                      placeholder='Count'
                      onChangeCallback={e => {
                        setVehicleValue('passengerCount', e);
                        clearErrors('passengerCount');
                      }}
                    />
                  </Box>

                  <Box>
                    <Controller
                      name='driverNumber'
                      control={control}
                      rules={{ required: true }}
                      render={({ field }) => (
                        <PhoneNoTextField
                          {...field}
                          setValue={setVehicleValue}
                          style='share'
                          label='Contact Number'
                          error={Boolean(vehicleErrors?.driverNumber?.message)}
                          helperText={vehicleErrors?.driverNumber?.message}
                          onChange={(e: any) => {
                            if (e) {
                              handleValidate(e);
                            }
                            trigger('driverNumber');
                          }}
                        />
                      )}
                    />
                    {/* {errors?.phone?.message && (
                    <Typography
                      sx={{
                        color: '#d32f2f',
                        display: 'flex',
                        justifyContent: 'flex-start',
                        fontSize: '12px',
                        fontWeight: 300,
                        mt: 0.5,
                        ml: 1
                      }}
                    >
                      {(errors as any).phone?.message}
                    </Typography>
                  )} */}
                      </Box>
                    </Box>
                  )}
                </DialogContent>

                {/* Footer */}
                <DialogActions
                  sx={{
                    borderTop: '1px solid',
                    borderColor: 'divider',
                    bgcolor: 'grey.50',
                    gap: 1.5,
                    p: 3
                  }}
                >
                  {/* <Button
                    onClick={handleCancel}
                    // disabled={dropdownLoading}
                    variant='outlined'
                    sx={{
                      px: 4,
                      py: 1.5,
                      minWidth: 100,
                      height: 42,
                      borderRadius: 2,
                      textTransform: 'none',
                      fontWeight: 600,
                      fontSize: '0.925rem',
                      borderColor: 'grey.300',
                      color: 'text.primary',
                      borderWidth: 1.5,
                      // '&:hover': {
                      //   borderColor: 'primary.main',
                      //   bgcolor: 'primary.light',
                      //   color: 'primary.main',
                      //   borderWidth: 1.5
                      // },
                      '&:disabled': {
                        opacity: 0.5,
                        borderColor: 'grey.300'
                      },
                      transition: 'all 0.2s ease-in-out'
                    }}
                  > */}
                  {/* Cancel */}
                  {/* </Button> */}
                  <CustomButton
                    className='cancel'
                    category='Cancel'
                    variant='outlined'
                    onClick={handleCancel}
                  />
                  <CustomButton
                    disabled={onsubmitIsLoading || PVTGRPUpdateLoading}
                    className='saveChanges'
                    category={'Save'}
                    type='submit'
                    // icon='mynaui:send-solid'
                    loading={onsubmitIsLoading || PVTGRPUpdateLoading}
                    // onClick={handleSendWhatsapp}
                  />
                  {/* <Button
                    disabled={onsubmitIsLoading || PVTGRPUpdateLoading}
                    variant='contained'
                    type='submit'
                    startIcon={
                      onsubmitIsLoading || PVTGRPUpdateLoading ? (
                        <CircularProgress size={16} color='inherit' />
                      ) : (
                        <Check />
                      )
                    }
                    sx={{
                      px: 4,
                      py: 1.5,
                      minWidth: 120,
                      height: 42,
                      borderRadius: 2,
                      textTransform: 'none',
                      fontWeight: 600,
                      fontSize: '0.925rem',
                      bgcolor: 'primary.main',
                      boxShadow: '0 2px 8px rgba(25, 118, 210, 0.3)',
                      '&:hover': {
                        bgcolor: 'primary.dark',
                        boxShadow: '0 4px 12px rgba(25, 118, 210, 0.4)',
                        transform: 'translateY(-1px)'
                      },
                      '&:active': {
                        transform: 'translateY(0)'
                      },
                      '&:disabled': {
                        opacity: 0.6,
                        boxShadow: 'none'
                      },
                      transition: 'all 0.2s ease-in-out'
                    }}
                  >
                    {onsubmitIsLoading || PVTGRPUpdateLoading ? 'Saving...' : 'Save'}
                  </Button> */}
                </DialogActions>
              </Box>
            </Dialog>
          )}
          {hotelGuestView && (
            <>
              <CustomButton
                className='cancel'
                category='Back'
                startIcon={<ArrowBackIcon />}
                onClick={() => {
                  setCallApi(false);
                  setHotelGuestView(null);
                }}
              />

              <TourDashboard selectedTour={hotelGuestView} />
            </>
          )}
          {isDialog === 'whatsapp' && (
            <Dialog open={isDialog === 'whatsapp'}>
              <Box
                sx={{
                  textAlign: 'center',
                  padding: '5%',
                  minWidth: '350px'
                }}
              >
                <Typography>{constant.ShareToWhatsapp}</Typography>
                <Box
                  sx={{
                    paddingTop: '5%',
                    display: 'flex',
                    flexDirection: 'row',
                    gap: '15px',
                    justifyContent: 'center'
                  }}
                >
                  <CustomButton
                    className='cancel'
                    category='Cancel'
                    variant='outlined'
                    onClick={() => {
                      setIsDialog('');
                      setCallApi(false);
                    }}
                  />
                  <CustomButton
                    className='saveChanges'
                    category={'Send'}
                    icon='mynaui:send-solid'
                    loading={sendwhatsapp?.isLoading}
                    onClick={handleSendWhatsapp}
                  />
                </Box>
              </Box>
            </Dialog>
          )}

          {isDialog == 'Nocontact' && (
            <Dialog
              open={isDialog == 'Nocontact'}
              onClose={handleClose}
              maxWidth='xl'
              fullWidth
              PaperProps={{
                sx: {
                  width: '90vw',
                  maxWidth: '1400px',
                  height: '85vh',
                  maxHeight: '800px',
                  borderRadius: '16px',
                  boxShadow: '0 24px 48px rgba(0, 0, 0, 0.15)',
                  background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)',
                  border: '1px solid rgba(226, 232, 240, 0.8)',
                  overflow: 'hidden'
                }
              }}
            >
              <Box
                sx={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  position: 'relative'
                }}
              >
                <Box
                  sx={{
                    padding: '10px 32px ',
                    borderBottom: '1px solid #e2e8f0',
                    background: 'linear-gradient(90deg, #f1f5f9 0%, #ffffff 100%)',
                    position: 'relative',
                    flexShrink: 0
                  }}
                >
                  <Box
                    sx={{
                      display: 'flex',
                      flexDirection: { xs: 'column', sm: 'row' },
                      alignItems: { xs: 'stretch', sm: 'flex-start' },
                      gap: { xs: '8px', sm: '12px' },
                      padding: { xs: '8px 12px', sm: '12px 16px' },
                      backgroundColor: '#fffbeb',
                      border: '1px solid #fed7aa',
                      borderRadius: '12px',
                      marginBottom: '16px',
                      boxShadow: '0 2px 4px rgba(251, 191, 36, 0.1)'
                    }}
                  >
                    <Box
                      sx={{
                        width: '16px',
                        height: '16px',
                        borderRadius: '50%',
                        backgroundColor: '#f59e0b',
                        color: '#ffffff',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '12px',
                        fontWeight: 'bold',
                        flexShrink: 0,
                        marginTop: { xs: 0, sm: '2px' }
                      }}
                    >
                      !
                    </Box>

                    <Box sx={{ flex: 1 }}>
                      <Typography
                        variant='body1'
                        sx={{
                          color: '#92400e',
                          fontSize: { xs: '11px', sm: '12px' },
                          lineHeight: 1.6,
                          fontWeight: 500,
                          margin: 0
                        }}
                      >
                        Some of these bookings do not have contact numbers. You may either
                        add the missing numbers or proceed by clicking the 'Skip' button
                        to send WhatsApp messages to the bookings with valid contact
                        numbers.
                      </Typography>
                    </Box>

                    <CustomButton
                      className='skip'
                      category='Skip & Send'
                      onClick={() => {
                        handleSkip();
                        setCallApi(false);
                      }}
                      sx={{
                        minWidth: { xs: '100%', sm: '100px' },
                        height: '36px',
                        borderRadius: '6px',
                        textTransform: 'none',
                        fontWeight: 600,
                        fontSize: { xs: '0.75rem', sm: '0.825rem' },
                        border: '2px solid #f59e0b',
                        color: '#f59e0b',
                        backgroundColor: '#ffffff',
                        boxShadow: '0 2px 4px rgba(245, 158, 11, 0.15)',
                        '&:hover': {
                          backgroundColor: '#fef3c7',
                          borderColor: '#d97706',
                          color: '#d97706',
                          transform: { xs: 'none', sm: 'translateY(-1px)' },
                          boxShadow: '0 4px 8px rgba(245, 158, 11, 0.25)'
                        },
                        transition: 'all 0.2s ease'
                      }}
                    />
                  </Box>
                </Box>
                <Box
                  sx={{
                    flex: 1,
                    // padding: 'px 28px',
                    display: 'flex',
                    flexDirection: 'column',
                    minHeight: 0,
                    overflow: 'hidden'
                  }}
                >
                  <Box
                    sx={{
                      height: '200vh',
                      borderRadius: '12px',
                      border: '1px solid #e2e8f0',
                      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
                      background: '#ffffff',
                      overflow: 'auto'
                    }}
                  >
                    <Box
                      key={invalidRows?.length}
                      sx={{
                        height: '100%',
                        width: '100%',
                        '& .MuiDataGrid-root': {
                          border: 'none',
                          height: '100%'
                        },
                        '& .MuiDataGrid-main': {
                          overflow: 'visible'
                        },
                        '& .MuiDataGrid-virtualScroller': {
                          overflow: 'auto !important',
                          height: 'auto !important'
                        },
                        '& .MuiDataGrid-footerContainer': {
                          minHeight: '52px',
                          borderTop: '1px solid #e2e8f0',
                          backgroundColor: '#f8fafc'
                        },
                        '& .MuiDataGrid-row:hover': {
                          backgroundColor: '#f1f5f9'
                        }
                      }}
                    >
                      <CustomDataGrid
                        rows={invalidRows}
                        columns={invalidColumns}
                        loading={isLoading}
                        rowHeight={40}
                        type={'noPageNation'}
                        paginationMode={'client'}
                      />
                    </Box>
                  </Box>
                </Box>

                <Box
                  sx={{
                    padding: { xs: '12px 16px', sm: '20px 32px 24px' },
                    borderTop: '1px solid #e2e8f0',
                    background: 'linear-gradient(90deg, #ffffff 0%, #f8fafc 100%)',
                    display: 'flex',
                    flexDirection: { xs: 'column', sm: 'row' },
                    justifyContent: 'space-between',
                    alignItems: { xs: 'stretch', sm: 'center' },
                    gap: { xs: '12px', sm: 0 },
                    flexShrink: 0
                  }}
                >
                  <Box
                    sx={{
                      display: 'flex',
                      flexDirection: { xs: 'column', sm: 'row-reverse' }, // update first on sm+
                      gap: { xs: '10px', sm: '16px' },
                      width: { xs: '100%', sm: 'auto' }
                    }}
                  >
                    <CustomButton
                      className='saveChanges'
                      type='submit'
                      disabled={invalidRows?.some((item: any) => item?.isError)}
                      category='Update'
                      onClick={() => handleUpdateContact()}
                      loading={updateGuestLoading}
                      sx={{
                        minWidth: { xs: '100%', sm: '120px' }
                        // height: '44px',
                        // borderRadius: '8px',
                        // textTransform: 'none',
                        // fontWeight: 600,
                        // fontSize: { xs: '0.875rem', sm: '0.925rem' },
                        // background: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
                        // color: '#ffffff',
                        // boxShadow: '0 4px 12px rgba(59, 130, 246, 0.3)',
                        // '&:hover': {
                        //   background: 'linear-gradient(135deg, #2563eb 0%, #1e40af 100%)',
                        //   transform: 'translateY(-2px)',
                        //   boxShadow: '0 8px 20px rgba(59, 130, 246, 0.4)'
                        // },
                        // transition: 'all 0.2s ease',
                        // '&:disabled': {
                        //   background: '#94a3b8',
                        //   transform: 'none',
                        //   boxShadow: 'none'
                        // }
                      }}
                    />
                    <CustomButton
                      className='cancel'
                      category='Cancel'
                      onClick={() => {
                        reset();
                        handleInvalidClose();
                        setCallApi(false);
                      }}
                      sx={{
                        minWidth: { xs: '100%', sm: '120px' }
                        // height: '44px',
                        // borderRadius: '8px',
                        // textTransform: 'none',
                        // fontWeight: 500,
                        // fontSize: { xs: '0.875rem', sm: '0.925rem' },
                        // border: '2px solid #e2e8f0',
                        // color: '#64748b',
                        // backgroundColor: '#ffffff',
                        // '&:hover': {
                        //   backgroundColor: '#f8fafc',
                        //   borderColor: '#cbd5e1',
                        //   transform: 'translateY(-1px)',
                        //   boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)'
                        // },
                        // transition: 'all 0.2s ease'
                      }}
                    />
                  </Box>

                  {invalidRows?.some((item: any) => item?.isError) && (
                    <Box
                      sx={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: { xs: 'flex-start', sm: 'flex-end' },
                        gap: '10px',
                        width: { xs: '100%', sm: 'auto' }
                      }}
                    >
                      <Box
                        sx={{
                          width: 15,
                          height: 15,
                          borderRadius: '50%',
                          backgroundColor: '#ff07078c'
                        }}
                      />
                      <Box>
                        <p
                          style={{
                            color: '#5e5c5cff',
                            fontSize: '14px',
                            fontWeight: 600,
                            fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif'
                          }}
                        >
                          Invalid Contact Numbers:{' '}
                          {invalidRows?.filter((item: any) => item?.isError)?.length}
                        </p>
                      </Box>
                    </Box>
                  )}
                </Box>
              </Box>
            </Dialog>
          )}
        </Box>
      ) : (
        <Box>
          {isViewAdhoc && (
            <ViewAdhocRequests
              onClose={() => setIsDialog('')}
              currentDatas={ViewAdhocReqData}
              columns={adhocReqColumns}
              PageNo={PageNo}
              PageSize={PageSize}
              refreshLoader={refreshLoader}
              handlePaginationModelChange={handlePaginationAdhocReq}
              handleHotelsandGuestsView={handleHotelsandGuestsView}
              setSelectedTripRow={setSelectedTripRow}
              setIsDialog={setIsDialog}
              setIsViewAdhoc={setIsViewAdhoc}
              setCallApi={setCallApi}
            />
          )}
        </Box>
      )}
      {isDialog === 'adhoc' && (
        <AddAdhocTrip
          setCallApi={setCallApi}
          isOpen={isDialog === 'adhoc'}
          setIsOpen={setIsDialog}
          selectedRow={selectedTripRow}
          setSelectedRow={setSelectedTripRow}
          pageDetailss={{ pageNo: PageNo, pageSize: PageSize }}
          Agents={agentNames}
          autoplannerID={autoplannerID}
          isOverview={isOverview}
          Routes={[]}
          isViewAdhoc={isViewAdhoc}
          setBadgeCount={setBadgeCount}
        />
      )}
      {isDialog === 'delete' && (
        <Dialog open={isDialog === 'delete'}>
          <Box
            sx={{
              textAlign: 'center',
              padding: '5%',
              minWidth: '350px'
            }}
          >
            <Typography>Are you sure want to delete this booking?</Typography>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'row',
                paddingTop: '5%',
                justifyContent: 'center'
              }}
            >
              <Box sx={{ marginRight: '12px' }}>
                <CustomButton
                  className='saveChanges'
                  loading={AutoPlannerDeleteTripLoading}
                  category='Yes'
                  onClick={() => {
                    handleDeleteDriver();
                  }}
                />
              </Box>
              <CustomButton
                className='cancel'
                category='No'
                onClick={() => {
                  setIsDialog('');
                }}
              />
            </Box>
          </Box>
        </Dialog>
      )}
    </>
  );
};

export default TodayTours;
